# import

In [1]:
import sys
import os
from tqdm import tqdm

import torch

import matplotlib.pyplot as plt
import numpy as np

sys.path.append('../src/')
import utils
import dataloader
from train_utils import *
from model.AutoEncoder import EncoderBlock
from model.RDEC import RDEC

# set params

In [2]:
config = utils.readConfig('../config.json')

In [3]:
train_config = config['train_params']['train']

batch_size = train_config['batch_size']

model_config = config['model_params']
encoder_layers = model_config['encoder_layers']
num_clusters = model_config['num_clusters']
base_unit_num = model_config['base_unit_num']
emb_dim = model_config['emb_dim']

output_dir = '../data/test'
utils.makeDirs(output_dir)

weight_path = '../data/train/weights/RDEC.pth'

# load dataset

In [4]:
dataloaders, classes = dataloader.load_mnist('../data', batch_size)

# def model

In [5]:
encoder = EncoderBlock(encoder_layers, base_unit_num, emb_dim)
for input_data, label in dataloaders['train']:
    break
model = RDEC(encoder, num_clusters, input_data,)
model.load_state_dict(torch.load(weight_path))

<All keys matched successfully>

In [6]:
for imgs, labels in dataloaders['test']:
    break

In [7]:
idx = 1

In [11]:
q = model(imgs)
pred = q.argmax(1)

In [16]:
for i in range(num_clusters):
    print(label[pred==i].numpy())

[5 1 7 2 3 3 8 8 0 8 3 7 3 8 4 0 3 2 3 1 5 4 3 9 4 5 8 5 3 0 4 0 5 5 0 2 8
 8 5 7 1 3 1 0 5 7 3 6 1 9 1 0 9 8 1 1 5 1 7 9 0 1 9 2 0 1 4 2 6 9 5 2 0 8
 5 4 0 1 3 5 8 9 4 0 6 4 1 2 8 5 3 5 3 7 5 7 9 1 2 0 5 0 9 1 1 6 6 3 2 7 2
 6 1 9 5 5 8 1 5 9 3 8 9 7 6 2 0]
[2 8 8 2 6 9 0 8 9 8 8 0 0 1 5 2 0 5 3 4 1 8 6 1 4 2 8 3 6 1 2 8 9 7 4 8 0
 3 0 8 5 2 8 7 7 0 1 6 8]
[3 2 5 7 2 9 3 9 3 5 1 3 3 6 1 2 7 8 1 3 2 4 3 2 2 7]
[2 2 5 1 4 0 2 3 0 3 5 5 0 7 0 5 1 7 7 6 2 8 7 9 3 6 2 2]
[2 1 7 0 8 4 0 1 1 6 9 8 2 9 5 0 3 0 3 7 4 4 1 2 5 1 5 7 4 9 2 5 8 1 8 5 0
 1 5 3 3 0 7 6 2 3 6 8 7 5 8 0 2 9 6 3 5 6 8 9 5 8 1 4 8 3 2 6 7 0 5 0 9 0
 9 9 1 7 0]
[5 1 7 9 2 8 8 6 7 4 5 7 2 3 1 5 3 4 5 0 5 7 6 4 7 4 8 0 3 7]
[3 5 5 2 6 8 9 5 2 7 4 2 6 9 6 3 2 7 8 0 3 8 6 9 2 8 1 4 1 2 6 5 5 7 2 3 0
 6 8 7 9 6 9 1 1]
[9 6 5 0 7 2 7 3 4 1 9 1 2 1 7 1 6 1]
[9 0 7 3 1 0 2 7 2 0 5 7 2 6 8 1 4 9 1 4 9 4 6 3 7 7 2 5 1 4 8 0 8 1 8 3 1
 1 3 4 3 9 3 6 3 9 3 7 4 8 5 7 8 4]
[6 3 0 9 6 9 0 3 0 0 1 2 7 3 6 5 9 4 6 6 4 1 6 9 7 8 7 1 7 3 6